```{r setup, include=FALSE}
# This is a [Reactor](https://github.com/herbps10/reactor) notebook. Here's how to run this notebook in Reactor: 

# ```
# library(reactor)
# 
# notebook <- ReactorNotebook$load('Rmd')
# start_reactor(notebook)
# ```

library(reactor)
```

```{r f1ca1450-d284-11ea-b11b-7dbd38ed4601, position=1, open=FALSE, hasImage=FALSE, echo=FALSE, results='asis'}
md("
# Gaussian Processes

Let $\\{Y_t\\}$ be a stochastic process indexed by $t\\in\\mathbb{R}$. We call $\\{Y_t\\}$ a _Gaussian Process_ if any finite set of draws $\\boldsymbol{y}$  from the process at points $\\boldsymbol{t}$ is multivariate normally distributed:
$$
\\boldsymbol{y} \\sim \\mathcal{MVN}\\left(m(\\boldsymbol{t}), k(\\boldsymbol{t}, \\boldsymbol{t}) \\right)
$$
where $m(\\boldsymbol{t})$ is a _mean function_ and $k(\\boldsymbol{t}, \\boldsymbol{t})$ is a _kernel function_ that gives the covariance between every point in $\\boldsymbol{t}$.

For this notebook, we assume the mean function is zero: $m(\\cdot) = 0$.

A popular choice of kernel is the squared exponential function:
$$
k_{SQ}(t_1, t_2) = \\sigma^2 \\exp\\left(-\\frac{(t_1 - t_2)^2}{2\\lambda^2} \\right)
$$
")
```

```{r 07dd3690-d286-11ea-b11b-7dbd38ed4601, position=2, open=FALSE, hasImage=FALSE, echo=TRUE}
squared_exponential_kernel <- function(t1, t2, sigma, lambda) sigma^2 * exp(-(t1 - t2)^2 / (2 * lambda^2))
```

```{r 21b54580-d286-11ea-b11b-7dbd38ed4601, position=3, open=FALSE, hasImage=FALSE, echo=FALSE, results='asis'}
md("
We can draw from a Gaussian Process at points $\\boldsymbol{t}$ by drawing from a multivariate normal distribution with mean zero and covariance computed using the kernel function.
")
```

```{r 4f2b7480-d286-11ea-b11b-7dbd38ed4601, position=4, open=FALSE, hasImage=FALSE, echo=TRUE}
sigma <- slider(min = 0.1, max = 1, title = "Sigma: covariance scale parameter", step = 0.01, value = 0.5)
```

```{r 5846d870-d286-11ea-b11b-7dbd38ed4601, position=5, open=FALSE, hasImage=FALSE, echo=TRUE}
lambda <- slider(min = 0.1, max = 5, step = 0.01, value = 3, title = "Lambda: length-scale parameter")
```

```{r b3329a30-d286-11ea-b11b-7dbd38ed4601, position=6, open=TRUE, hasImage=TRUE, viewWidth=0.344632768361582, echo=TRUE}
{
	t <- 20
    mu <- rep(0, t)
    Sigma <- outer(1:t, 1:t, squared_exponential_kernel, sigma, lambda)
    draws <- mvtnorm::rmvnorm(5, mu, Sigma) 
    
    matplot(t(draws), type = 'l')
}
```
